version: "23.0.5"
services:
  discovery:
    build: ./eureka-server
    ports:
    - 8761:8761
    image: eureka_image

  post:
    build: ./posts
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 8088:8088
    image: post-service
    depends_on:
    - discovery

  comment:
    build: ./comments
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 8081:8081
    image: comments-service
    depends_on:
    - discovery