version: "3.8"
services:
  discovery:
    build: ./eureka-server
    ports:
      - 8761:8761
    image: eureka_image

  mysqldb:
    container_name: container_mysql
    image: "mysql:5.7"
    restart: always
    ports:
      - 3308:3306
    networks:
      - network_mysql


  post:
    build: ./posts
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8088:8088
    image: post-service
    depends_on:
      - discovery

  comment:
    build: ./comments
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8081:8081
    image: comments-service
    depends_on:
      - discovery
      - mysqldb
    networks:
      - network_mysql

  gateway:
    build: ./api-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8083:8083
    image: api_gateway
    depends_on:
      - discovery

networks:
  network_mysql:
    external: true
