version: "23.0.5"
services:
  discovery:
    build: ./eureka-server
    ports:
    - 8761:8761
    image: eureka_image

  post:
    build: ./posts
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 8088:8088
    image: post-service
    depends_on:
    - discovery


  category:
    build: ./category
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8082:8082
    image: category-service
    depends_on:
      - discovery