version: "23.0.5"
services:
  mongo_db:
    container_name: mongo_db
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    expose:
      - "27017"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
  #     ME_CONFIG_MONGODB_URL: mongodb://localhost:27017
  # mongodb_posts:
    # image: mongodb_posts
    # ports:
    #   - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin


  discovery:
    build: ./eureka-server
    ports:
    - 8761:8761
    image: eureka_image


  post:
    build: ./posts
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    - spring.data.mongodb.host=mongo_db
    - spring.data.mongodb.port=27017
    - spring.data.mongodb.database=posts
    ports:
    - 8090:8090
    image: posts-service
    depends_on:
    - mongo_db
    - discovery


  gateway:
    build: ./api-gateway
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 8081:8081
    image: api_gateway
    depends_on:
    - discovery
