version: "3.8"
services:
  mongo_db:
    container_name: mongo_db
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    expose:
      - "27017"

  # users_mongo_db:
  #   container_name: users_mongo_db
  #   image: "mongo:latest"
  #   restart: always
  #   ports:
  #     - 27018:27017
  #   expose:
  #     - "27018"

  discovery:
    build: ./eureka-server
    ports:
      - 8761:8761
    image: eureka_image

  mysqldb:
    container_name: mysqldb
    image: "mysql:5.7"
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=microcomments
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/microcomments
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - jpa.hibernate.ddl-auto=update
      - jpa.show-sql=true
      - jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - spring.main.web-application-type=reactive

  post:
    build: ./posts
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.data.mongodb.host=mongo_db
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=posts
      - spring.config.import=optional:configserver:http://discovery:8761
    ports:
      - 8090:8090
    image: posts-service
    depends_on:
      - mongo_db
      - discovery

  gateway:
    build: ./api-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      # - spring.cloud.config.enabled=false
      # - eureka.client.register-with-eureka = true
      # - spring.cloud.gateway.discovery.locator.enabled= true
      # - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/auth/realms/jobBoardKeyCloak
      # - keycloak.auth-server-url=http://localhost:8180/auth
      # - keycloak.realm=jobBoardKeyCloak
      # - keycloak.resource=candidat-service
      # - keycloak.public-client=true
      # - keycloak.use-resource-role-mappings=true

    ports:
      - 8081:8081
    image: api_gateway
    depends_on:
      - discovery

  quizz:
    build: ./quizz-app
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.url=jdbc:h2:file:./data/testdb
      - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      - spring.datasource.driver-class-name=org.h2.Driver
      - jpa.hibernate.ddl-auto=update
      - spring.config.import=optional:configserver:http://discovery:8761
      - spring.jpa.defer-datasource-initialization=true
    ports:
      - 8009:8009
    image: quizz-service
    depends_on:
      - discovery

  comment:
    build: ./comments
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - MYSQL_DATABASE=microcomments
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8085:8085
    image: comments-service
    depends_on:
      - discovery
      - mysqldb

  cours:
    build: ./cours
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.url=jdbc:h2:file:./db/h2test.db
      - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      - spring.datasource.driver-class-name=org.h2.Driver
      - jpa.hibernate.ddl-auto=update
      - spring.config.import=optional:configserver:http://discovery:8761
      - spring.jpa.defer-datasource-initialization=true
    ports:
      - 8082:8082
    image: cours-service
    depends_on:
      - discovery
  user:
    build: ./user
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.url=jdbc:h2:file:./data/testdb
      - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      - spring.datasource.driver-class-name=org.h2.Driver
      - jpa.hibernate.ddl-auto=update
      - spring.config.import=optional:configserver:http://discovery:8761
      - spring.jpa.defer-datasource-initialization=true
      - keycloak.auth-server-url=http://keycloak:8180/auth
      - keycloak.realm=jobBoardKeyCloak
      - keycloak.resource=candidat-service
      - keycloak.public-client=true
      - keycloak.use-resource-role-mappings=true
    ports:
    - 7070:7070
    image: user-service
    depends_on:
    - discovery
    - keycloak
  keycloak:
    container_name: keycloak
    #build: ./keycloak
    ports:
    - 8180:8180
    image: keycloak
