version: "23.0.5"
services:
  discovery:
    build: ./eureka-server
    ports:
    - 8761:8761
    image: eureka_image



  cours:
    build: ./cours
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8082:8082
    image: cours-service
    depends_on:
      - discovery

  gateway:
    build: ./api-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8081:8081
    image: api_gateway
    depends_on:
      - discovery
