version: "23.0.5"
services:
  discovery:
    build: ./eureka-server
    ports:
    - 8761:8761
    image: eureka_image

  post:
    build: ./posts
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 8088:8088
    image: post-service
    depends_on:
    - discovery
  
  quizz:
    build: ./quizz-app
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 8009:8009
    image: quizz-service
    depends_on:
    - discovery